### ISSUE TITLE
Policy Gradient Calculation

### ISSUE THREAD

**Issue by NiklasZ** [vwxyzjn/gym-microrts-paper#3]
Hi,

I'm working on writing some new policy networks using your code and noticed that you have a critic network as well to calculate the Generalized Advantage Estimate (GAE). Your blog only references a discounted return in the policy gradient though:

![image](https://user-images.githubusercontent.com/7795825/169847161-2743d757-df72-47c9-a4a3-ae6dc0db1aed.png)

I'm still a bit new to PPO, so can you please clarify which is correct? This is my first time using PPO, so I want to be sure I understand the training properly.

Thanks!

Really appreciate the blog post by the way. It's really helpful :smile:

**Comment by vwxyzjn** [comment]
Hey, thanks for opening up an issue. You are absolutely right: the implementation uses GAE. Here the blog only demonstrates how action components work with policy gradient. For more info on GAE, please checkout our latest blog post / paper: https://iclr-blog-track.github.io/2022/03/25/ppo-implementation-details/

**Comment by NiklasZ** [comment]
Ok thanks this explains the discrepancy
