### ISSUE TITLE
Reward Weight Array

### ISSUE THREAD

**Issue by NiklasZ** [vwxyzjn/gym-microrts-paper#4]
Hi, 

In the agent files, a reward weighting array is specified (for example [here](https://github.com/vwxyzjn/gym-microrts-paper/blob/master/ppo_diverse_impala.py#L200)):

```python
envs = MicroRTSVecEnv(
    num_envs=args.num_envs,
    max_steps=2000,
    render_theme=2,
    ai2s=[microrts_ai.coacAI for _ in range(args.num_envs-6)] + \
        [microrts_ai.randomBiasedAI for _ in range(2)] + \
        [microrts_ai.lightRushAI for _ in range(2)] + \
        [microrts_ai.workerRushAI for _ in range(2)],
    map_path="maps/16x16/basesWorkers16x16.xml",
    reward_weight=np.array([10.0, 1.0, 1.0, 0.2, 1.0, 4.0]) # <-- This line
)
```

It's not really clear to me which shaped reward each weighting is combined with. I can make some educated guesses based on the [article](https://wandb.ai/vwxyzjn/gym-microrts-paper/reports/Gym-RTS-Toward-Affordable-Deep-Reinforcement-Learning-Research-in-Real-Time-Strategy-Games--Vmlldzo2MDIzMTg), but the `1.0` weights are not distinguishable. Can you please explain which is which?

Thanks!

**Comment by vwxyzjn** [comment]
The reward weight array corresponds to these reward functions - 

```
                WinLossRewardFunction(),
                ResourceGatherRewardFunction(),
                ProduceWorkerRewardFunction(),
                ProduceBuildingRewardFunction(),
                AttackRewardFunction(),
                ProduceCombatUnitRewardFunction(),
```


https://github.com/vwxyzjn/gym-microrts/blob/91d586d1e39a59037f36085b9484304286a594a8/gym_microrts/envs/vec_env.py#L104-L110

**Comment by NiklasZ** [comment]
Ah, thanks for pointing it out :+1:
