### ISSUE TITLE
WARNING: TrainDirection invalid direction - possible bug?

### ISSUE THREAD

**Issue by NiklasZ** [vwxyzjn/gym-microrts-paper#5]
Hi,
I recently down-sized the `ppo_gridnet_diverse_impala.py` to use the `maps/8x8/basesWorkers8x8.xml` instead of the `maps/16x16/basesWorkers16x16.xml` map, in order to get some faster feedback during training (modified file: [ppo_gridnet_diverse_impala.py.zip](https://github.com/vwxyzjn/gym-microrts-paper/files/8837184/ppo_gridnet_diverse_impala.py.zip)). 

While running it, I'm encountering a lot of `WARNING: TrainDirection invalid direction` in the action log. I get similar results when I do this for other agents like `ppo_diverse_impala.py`. Here an example:

```
global_step=12046680, episode_reward=71.0
global_step=12046704, episode_reward=58.0
global_step=12047712, episode_reward=46.20000076293945
WARNING: TrainDirection invalid direction
WARNING: TrainDirection invalid direction
WARNING: TrainDirection invalid direction
WARNING: TrainDirection invalid direction
WARNING: TrainDirection invalid direction
```

I'm guessing this is due to units attempting to train new units where there is no space. I'd have a go at fixing this myself, but am a bit lost on how the masking works in `get_action()`. Can you provide some pointers, please? For example, why are we using a different masking during exploration vs. learning?

**Comment by vwxyzjn** [comment]
This message was from CoacAI - https://github.com/Coac/coac-ai-microrts/blob/0c992fd1aa0d59867dfbd4ad8fe445c62e733f62/src/ai/coac/TrainDirection.java#L58. Unfortunately this is an upstream issue we can't fix :)

**Comment by NiklasZ** [comment]
Oh I figured this is coming from the wrapped Java environment. I'm gonna see if I can write a performance-friendly mask that fixes it.

**Comment by vwxyzjn** [comment]
There is probably not much we can do other than compiling a different version of CoacAI that does not do the warning :)

**Comment by NiklasZ** [comment]
Ah wait, this is caused by CoacAI? I thought this was an issue with the RL agents. Ok now I understand what you mean :)
Yeah then there's not much we can do.
